

import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  RefreshControl,
  Alert,
  Share, // Native RN Share for text messages
} from 'react-native';
import * as Print from 'expo-print'; // Expo PDF library
import * as Sharing from 'expo-sharing'; // Expo Sharing library
import { thermalAPI } from '../config/api';
import Card from '../components/Card';
import Button from '../components/Button';

const AnalysisScreen = ({ route }) => {
  const { thermalId } = route.params;
  const [thermalData, setThermalData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => {
    fetchAnalysis();
  }, []);

  const fetchAnalysis = async () => {
    try {
      const response = await thermalAPI.getOne(thermalId);
      setThermalData(response.data.data.thermalData);
      setLoading(false);
    } catch (error) {
      console.error('Fetch error:', error);
      Alert.alert('Error', 'Failed to load analysis results');
      setLoading(false);
    }
  };

  const onRefresh = async () => {
    setRefreshing(true);
    await fetchAnalysis();
    setRefreshing(false);
  };

  // Logic to share a text message summary
  const handleShare = async () => {
    const message = `🌱 Farm Analysis Report for ${thermalData.cropId?.cropName}\n` +
                    `Efficiency Score: ${thermalData.analysis.efficiencyScore}%\n` +
                    `AI Recommendation: ${thermalData.analysis.recommendations.split('\n')[0]}`;
    
    try {
      await Share.share({
        message: message,
      });
    } catch (err) {
      console.log('Sharing error:', err);
    }
  };

  // Logic to generate PDF and open the file share/download menu
  const generatePDF = async () => {
    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
            h1 { color: #16a34a; border-bottom: 2px solid #16a34a; padding-bottom: 10px; }
            .score-box { background: #f0fdf4; padding: 15px; border-radius: 8px; margin: 20px 0; }
            .label { font-weight: bold; color: #666; }
          </style>
        </head>
        <body>
          <h1>Crop Analysis Report</h1>
          <p><span class="label">Crop:</span> ${thermalData.cropId?.cropName || 'N/A'}</p>
          <p><span class="label">Date:</span> ${new Date(thermalData.measurementDate).toLocaleDateString()}</p>
          
          <div class="score-box">
            <h2>Efficiency Score: ${thermalData.analysis.efficiencyScore}%</h2>
            <p><span class="label">Status:</span> ${thermalData.analysis.stressLevel.toUpperCase()} Stress</p>
          </div>

          <h3>AI Recommendations:</h3>
          <p>${thermalData.analysis.recommendations.replace(/\n/g, '<br/>')}</p>
          
          <hr/>
          <p style="font-size: 10px; color: #999;">Generated by Smart Farming AI Mobile App</p>
        </body>
      </html>
    `;

    try {
      // 1. Generate the PDF file
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      
      // 2. Open the sharing menu for the PDF file
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Download or Share Analysis Report',
        UTI: 'com.adobe.pdf'
      });
    } catch (err) {
      console.error('PDF error:', err);
      Alert.alert('Error', 'Failed to generate and download PDF');
    }
  };

  if (loading) return <View style={styles.centerContainer}><Text>Loading analysis...</Text></View>;
  if (!thermalData || !thermalData.processed) return <View style={styles.centerContainer}><Text>No analysis available</Text></View>;

  const { analysis } = thermalData;
  const getEfficiencyColor = (score) => score >= 75 ? '#16a34a' : score >= 50 ? '#ca8a04' : '#ef4444';

  return (
    <ScrollView 
      style={styles.container} 
      refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
    >
      <View style={styles.content}>
        <Card>
          <Text style={styles.cardTitle}>Analysis Results</Text>
          <Text style={styles.subtitle}>{thermalData.cropId?.cropName} • {new Date(thermalData.measurementDate).toLocaleDateString()}</Text>
        </Card>

        <Card>
          <Text style={styles.cardTitle}>Efficiency Score</Text>
          <View style={styles.efficiencyContainer}>
            <Text style={[styles.efficiencyScore, { color: getEfficiencyColor(analysis.efficiencyScore) }]}>{analysis.efficiencyScore}%</Text>
            <Text style={styles.efficiencyLabel}>AI Generated Score</Text>
          </View>
        </Card>

        <Card>
          <Text style={styles.cardTitle}>AI Recommendations</Text>
          {analysis.recommendations.split('\n').filter(r => r.trim()).map((rec, index) => (
            <View key={index} style={styles.recommendation}>
              <Text style={styles.recommendationBullet}>✓</Text>
              <Text style={styles.recommendationText}>{rec}</Text>
            </View>
          ))}
        </Card>

        {/* Action Buttons */}
        <View style={styles.actionRow}>
          <Button title="Share Info" onPress={handleShare} variant="secondary" style={styles.flex1} />
          <View style={{ width: 10 }} />
          <Button title="Download PDF" onPress={generatePDF} style={styles.flex1} />
        </View>
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f3f4f6' },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  content: { padding: 20, paddingBottom: 40 },
  cardTitle: { fontSize: 18, fontWeight: 'bold', color: '#1f2937', marginBottom: 12 },
  subtitle: { fontSize: 14, color: '#6b7280' },
  efficiencyContainer: { alignItems: 'center', marginVertical: 20 },
  efficiencyScore: { fontSize: 60, fontWeight: 'bold' },
  efficiencyLabel: { fontSize: 12, color: '#9ca3af', marginTop: 5 },
  recommendation: { flexDirection: 'row', marginBottom: 12, padding: 12, backgroundColor: '#f0fdf4', borderRadius: 8 },
  recommendationBullet: { color: '#16a34a', fontSize: 16, fontWeight: 'bold', marginRight: 8 },
  recommendationText: { flex: 1, fontSize: 14, color: '#1f2937', lineHeight: 20 },
  actionRow: { flexDirection: 'row', marginTop: 20, marginBottom: 20 },
  flex1: { flex: 1 }
});

export default AnalysisScreen;